### ISSUE TITLE
Angular 2 integration with rxjs/observables

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers-docs#225]
Hi Feathers team,

Is it possible to add an Angular 2 (final) integration guide where Obserables/rxjs is used?

Keep up the good work!

Best regards
Patrick

**Comment by daffl** [comment]
This is unfortunately not anything the core team can take on at the moment since nobody is using Angular 2. I know @harangue has done some work with Angular 2 (and also wrote the original Angular guide). For RxJS integration definitely have a look at [feathers-reactive](https://github.com/feathersjs/feathers-reactive/).

**Comment by harangue** [comment]
@patrickpereira Hey Patrick, if there are any specific questions you have, I'd be happy to help out. For the most part, I think if you understand Angular 2 service architecture well Feathers should hopefully fit in quite naturally.

**Comment by mastertinner** [comment]
I wrote a blog post about that some time ago: https://berndsgn.ch/angular2-and-feathersjs/
Hope it helps.

**Comment by marshallswain** [comment]
@mastertinner Cool!  I added a link to your blog post to the tutorials and examples section of the [Built with Feathers](https://docs.feathersjs.com/why/showcase.html) page.  Thank you!

**Comment by marshallswain** [comment]
I also added a note with a link to the blog post to the Angular2 Frameworks tutorial.  I'm going to close this, now.  Please reopen if you feel it's needed, @patrickpereira.

**Comment by mastertinner** [comment]
Awesome! Thanks, @marshallswain!
