### ISSUE TITLE
Restructure Docs for Auk

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-docs#251]
This might be a pain because we'll have to check for broken links. However, we need to make it easier for people to find information and understand how the core pieces of feathers fit together so that they can get to the "Aha!" moment earlier.

We should tag the old version so that people can still view it in Github. Especially since it is still pretty navigable.
### Suggested Changes
- Have a short overview section of the parts of feathers with a diagram of data flow
  - **Hooks** are for manipulating/filtering data in/out and managing workflows by calling out to other services or APIs, and emitting events. They allow you to guarantee workflow order and make it easy to reason about ~application state~ your business logic and data as it flows through your app.
  - **Services** are objects that expose a consistent interface to a datastore, API or internal object so that they can be interchangeable
  - **Filters** are for filtering events before they are actually dispatched to connected clients
- A quick start guide/video or link to one
- Move everything else to be more API centric and less book like
- Bring FAQ top level

**Comment by daffl** [comment]
A smaller thing from my comment at https://github.com/feathersjs/feathers-docs/issues/210#issuecomment-254253136 is that I think we can remove the "Feathers vs. X" detailed pages and just turn them into blog posts. It's hard to keep them up to date and it isn't really documentation related.

**Comment by ekryski** [comment]
Agreed. They should come out of the docs and maybe moved to the blog or website for SEO and educational value. Like a lot of the content in the docs they muddy things up.

In order to address @marshallswain's concern I was thinking that the next version of the site will use Metalsmith so pages like that can be in Markdown and people can still edit them. If we are short on time we could hard code them on the site or not include them for now.

**Comment by daffl** [comment]
Here is my initial suggestion for the updated outline:

- Introduction
- How Feathers Works
- Getting started
  - Setting up
  - Scaffolding and services
  - Authentication
  - Manipulating data
  - Building a frontend
- Services
- Hooks
- REST APIs
  - Configuration
  - Routing, middleware, versioning
  - Error handling
- Realtime APIs
  - Service events
  - Event filtering
  - Socket.io
  - Primus
- Authentication
  - Strategies
    - Username/Password
    - API Key
    - OAuth (Google, Facebook)
    - Passwordless
  - Password management
  - Permissions
  - Client use
    - HTTP
    - Websockets
- Clients and Frameworks
  - Feathers client
    - REST
    - Socket.io
    - Primus
  - Frameworks
    - React
    - React Native
    - Angular 2
    - Vue.js
    - jQuery
  - Direct connection
    - REST
    - Socket.io
    - Primus
- Databases
  - Adapter basics
    - Pagination, sorting, selecting
    - Querying
    - Extending
  - NoSQL
    - In Memory
    - LocalStorage/AsyncStorage
    - Mongoose
    - MongoDB
    - NeDB
    - RethinkDB
  - SQL
    - KnexJS
    - Sequelize
- Ecosystem
  - feathers
  - feathers-rest
  - Feathers-socketio
  - Feathers-primus
  - Feathers-hooks
  - Feathers-hooks-common
  - Feathers-configuration
  - feathers-errors
  - …
- Help
  - FAQ
  - Contributing
  - Changelog
- License

@feathersjs/core-team

**Comment by daffl** [comment]
We probably also want to discuss the structure for each article and how parameters should be formatted so that the important information (like the API docs) are always located at the same spot. E.g.

--

## Summary

### `app.x()`

Thing that does X

__Options:__

- `foo` - Sets the foo parameter
- `bar` - Sets the bar parameter

## Example

```js
app.x()
```

## Usage

Here the detailed chatty stuff.

## Topic X

Any other topics as well.

**Comment by eddyystop** [comment]
The documents change, especially when new features are added. What do you think about having a What's New section. Current Feathers users can use it to keep on top of changes and new features.

**Comment by ekryski** [comment]
@daffl your suggested layout looks good to me! I think we should bring FAQ, Changelog and Contributing top level.

For frameworks are you thinking they are currently the way they are or should they be more API focused examples and move the more wordy guides to Medium?

We also might want to have a "New to Node" area that some people can skip. I've had some great feedback from a couple people that we are assuming too much NodeJS/Express knowledge. Someone new to node may not know how the ecosystem works, what express or express middleware is. I'm not sure if that should be really short section just after the "Introduction" or if it should be a Feathers post on Medium.

@eddyystop I like that idea. It would be good to highlight new stuff. However, I'm wondering if really that's what the release posts should be about.

I was thinking that if we decided to customize our docs with metalsmith we could have a "new" or "updated" badge in the nav beside each new section. However, whether we have badges or a dedicated section in the docs we'll need to keep it up to date and remove things as they become less new. If that's the case it would be good to define how long something is "new".

**Comment by ekryski** [comment]
I also do really like how Evan has Vuejs laid out. https://vuejs.org

It's kind of nice that he has API, Guide, Examples split as separate sections. I mean we have the them split up the same way on our main site but our current version of the docs is a mix between a guide/book and API docs. They really should be separate.

Vue's docs are API docs, and the guide is more like our docs are right now.

Our docs should probably just primarily be API docs, a guide could be a free or paid book, and individual guides/examples can point to the Guides/Examples collections in Medium. We can link to appropriate github repos, gists or jsfiddles for those right in the guide. Thoughts?

**Comment by ekryski** [comment]
These are our top 25 pages:

![screen shot 2016-11-03 at 2 51 51 pm](https://cloud.githubusercontent.com/assets/599019/19984689/1a9eb834-a1d5-11e6-883e-0748be304fd7.png)

**Comment by daffl** [comment]
Yes, I was thinking Ecosystem page should have a list of all official Feathers plugins and then the content from the "Showcase" page. The Ecosystem sub-sections would be links to all official Feathers plugins. They'd either have their own page (e.g. what is "Error Handling" now would become the page for `feathers-errors`, "Configuration" would become `feathers-configuration` etc. - that way we can add new plugins without having to figure out where they might fit in) or link to the existing documentation section (e.g. `feathers-socketio` would link to "Realtime/SocketIO", feathers-rest to "REST/Configuration").

The top 25 list is really helpful. We should probably keep those in one form or another (maybe a "Why Feathers" section with links to blog posts?). Having a "New to Node" section is a great idea, too. We probably want to expand on that eventually anyway. We probably want to keep the "What's new" stuff in the release posts for now.

Personally the differentiation between API and guides never made much sense to me. Say I'm reading the "Event filtering" section and it links to "Service events". Do I want to read the guide because I skipped it or do I just quickly want to look up the API for how to listen to them and what the available events are? I'm hoping that if we stick with the page layout I proposed (Summary and API, Example, In-Depth explanations) everywhere it would make a good middle ground. I don't even think we have to change too much in our docs. I'll start the branch and commit some examples of what I was thinking.

I have some reservations about using Metalsmith for generating the docs but we can discuss that further later.

**Comment by daffl** [comment]
Also, we can probably drop the changelog completely and just link to each repositories generated changelog.

I'm thinking we should at least keep the important framework chat app guides (and a page for "Others" or "My framework" or something). Otherwise I'm expecting lots of "How do I use this with <popular thing>" questions. We can move the more esoteric ones that are not likely to be updated frequently in the blog.

**Comment by daffl** [comment]
The final structure of the API docs (and current guide restructuring) can be found in the [auk-reorg branch](https://github.com/feathersjs/feathers-docs/tree/auk-reorg) viewed at https://docs.feathersjs.com/v/auk-reorg/api/readme.html
