### ISSUE TITLE
Ihave a question about feathers-doc  test using mocha and chai.

### ISSUE THREAD

**Issue by Luncher** [feathersjs/feathers-docs#347]
I see such a code

```javascript

      chai.request(app)
          //request to /store
          .post('/menus')
          .set('Accept', 'application/json')
          .set('Authorization', 'Bearer '.concat(token))

```

what mean  'Bearer '.concat(token) ? 

When I removed the **Bearer** can also work!!!

**Comment by marshallswain** [comment]
`Bearer <token>` is the standard format for authenticating over the `Authorization` header.  The client must send it in order to make an authenticated request.  If you read the Authorization section in the docs, you'll get a better idea of how to deny requests that don't have it.

Can you link the line number of that test?

**Comment by Luncher** [comment]
thanks for your reply!


the Screenshots:
![2016-12-19 11 26 34](https://cloud.githubusercontent.com/assets/5138977/21300342/16f60af2-c5de-11e6-8bec-5245877b0bb0.png)


My question is, why when I 'Bearer` deleted, token check can still be passed!

**Comment by Luncher** [comment]
Through some information I may already know where the problem, [authentication without Bearer](http://stackoverflow.com/questions/36574800/successful-request-despite-missing-bearer). 


But I have not seen chai-http source code, `Bearer` confirmation is the default authentication type.

**Comment by ekryski** [comment]
Yes you can use `Bearer` or not. Both will work. It's up to you. I think this is resolved 😄
