### ISSUE TITLE
Sequelize migrations confusion?

### ISSUE THREAD

**Issue by mmucklo** [feathersjs/feathers-docs#403]
I'm a bit new to feathersjs, so please excuse any ignorant questions.

I'm having some trouble understanding migrations in the context of Sequelize.

I've been following the documentation online.  First I got the messages service setup, with an additional service for users, and then a custom service I wrote.

All backed by a fresh postgres instance.

Everything was working fine, except someone I was working with said that the tables weren't created when he went to bring the service up.

I read the docs on migrations, and setup the config files according to the docs online for Sequelize and feathers.  The weird thing is if delete all the tables, create a blank migration, it seems to recreate all the tables even without specifying their schemas in the migrations file.  However if I don't create a blank migrations file, sequelize db:migrate seems to do nothing.

So I'm assuming the tables are being created automatically based on the model definitions, which is great.

What happens if I want to add a new model, or a new field to a model - do I then need to add another blank migration file?

Confused as to how to proceed.

--Matt

**Comment by daffl** [comment]
I'm going to close this since the [migration guide](https://docs.feathersjs.com/api/databases/sequelize.html#migrations) has been and the [new generator](https://docs.feathersjs.com/guides/step-by-step/generators/readme.html) (`npm install feathers-cli -g`) creates a more Sequelize and migration friendly setup (thanks to https://github.com/feathersjs/generator-feathers/pull/162).
