### ISSUE TITLE
Write a guide on deploying to AWS

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-docs#68]

**Comment by Mentioum** [comment]
Is there a particular way you had in mind for doing this?  There are a few different ways of varying difficulties.  Depending on what you want I don't mind doing this when I have some spare time.

- Standalone EC2 instance.
- Load Balanced EC2 instances with nginx. (manual configuration)
- EBS with Docker containers
- ... etc etc...

I'm assuming the most useful would be Standalone EC2 and EBS with Docker containers (because thats what all the cool kids want to see)?

**Comment by ekryski** [comment]
@Mentioum yup that's exactly what I was thinking. To be honest. Even just standalone EC2 so someone can see their app live would be a good start. Obviously once you tread into devops territory it gets a bit more specific and some people will be overwhelmed.

But if you are willing to tackle this it would be awesome! 🍻

**Comment by ekryski** [comment]
Note to self. If running behind a proxy that terminates SSL and using OAuth you will need to set:

```js
{
   "auth": {
    "facebook": {
       "callbackUrl": "https://domain.com/auth/facebook/callback"
    }
   }
}
```

To ensure that the callback is called with HTTPS and it runs back through your proxy.

**Comment by ekryski** [comment]
Unless someone else steps up we're likely not going to do this. I'd like to keep it very basic but given the number of variables in an AWS deploy and variance in infrastructure I'm going to close for now to keep issue triage easier. Happy to re-open if it comes up again or someone from the community wants to contribute.
