### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by kadams54** [feathersjs/feathers-docs#684]
Maybe this is a function of my dev env, but when I run:

`node ./examples/step/01/hooks/1.js`

I see:

~~~~
DEPRECATED. Use discard. (remove)
~~~~

The issue seems to be the remove hook. When I replace it with discard in `1.js` (lines 38 and 49) the message goes away.

**Comment by eddyystop** [comment]
`remove` is the same as `discard` but with extra "magic". `remove` was deprecated because we wanted that "magic" to be explicit.

You can replace `remove('name')` with `iff(isProvider('external'), discard('name))` as is mentioned in the docs. https://docs.feathersjs.com/api/hooks-common.html#discard .

The example will be changed when we remove `remove`.
