### ISSUE TITLE
Comment:Step-Intro-Not-worry

### ISSUE THREAD

**Issue by Harry97** [feathersjs/feathers-docs#696]
Comment:Step-Intro-Not-worry
It'd be nice if it had clarified whether Feather supports ES6 or not, and if not, how it can be added. Thanks!

**Comment by daffl** [comment]
Do you think that is necessary? You can use all language features that your version of Node supports or set up a transpiler like Babel which doesn't involve anything Feathers specific.

**Comment by Harry97** [comment]
@daffl As for the how to add it part, you're right, it'd be a bit of an overkill, but I do believe mentioning whether Feather supports ES6 features or not is important. I mean, you mention how you don't need to worry about setting up your front-end framework as it has its own dedicated section. I'm a bit of a novice anyway, so it's just my humble opinion. :)

**Comment by eddyystop** [comment]
What ES6 features were you wondering if Feathers supported?

**Comment by Harry97** [comment]
You know, the ones that node doesn't support yet, like import and what not.

**Comment by eddyystop** [comment]
This is really a Node issue, not a Feathers one, and more complicated that it appears. The guides don't try to teach Node and browser JS.

;tl:dr No one has import/export implemented per spec. Use https://caniuse.com/#index to answer questions.

What Chrome (hence also Node) supports changes frequently and, since the client also uses Feathers, you have to pay attention to what your target clients support.

Keeping track of this is a full time job and the go to resource for it is https://caniuse.com/#index

In practice you'll use Babel to build your client bundle, so you can code in anything Babel or its code-modifying plugin ecosystem support. You can also use Babel on the server code but, in practice, you code ES6 minus import and export to avoid having to run a build step.

The syntax specs of import and export are fixed, but the loading spec isn't yet. So no one has import/export implemented per spec. It'll be more complicated on browsers than for Node. Babel has a decent hack but it won't be compatible with the final spec. Node will require import/export be used only in *.jsm modules.

Feel free to reopen this issue.
