### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by jaysmathers** [feathersjs/feathers-docs#698]
Comment:Step-Basic-Db-connector

In the 1.js file I was confused by the missing schema model / table definition, (which is in 2 and 3.) Im suspect this has to do with NeDB details and not feathers but a single sentence could sooth brains like mine....

In the 3.js file there is an initial call to databaseConnect() at line 10 which should maybe be removed? Also the comments on lines 42/3 &47/8 are confusing to me.

**Comment by eddyystop** [comment]
Well 2.js and 3.js are not referred to in the guide. I originally intended to show use of 3 different DBs but later realized I didn't want to have people installing MongoDB or some Sequelize-supported DB. I included only NeDB because it requires zero setup.

The difference in models is because NeDB requires no model, while mongoose and sequelize do.

I believe sequelize requires the connect. The comments were notes to myself that its convenient to put the sequelize instance in the config, but to do that I needed app defined.

I'll remove 2.js and 3.js if this trips anyone else up.
