### ISSUE TITLE
Write a guide on deploying with pm2

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-docs#71]

**Comment by ekryski** [comment]
This may become part of #63. Since you can use whatever you want for a process monitor we're not going to bother with this in it's own guide. There are plenty of [tutorials out there are using pm2 with Express](http://blog.danyll.com/setting-up-express-with-nginx-and-pm2/), so it's exactly the same.

You can check out https://github.com/Unitech/pm2 for an API reference and all will work with Feathers.

**Comment by SephReed** [comment]
The reason this needs a guide is that feathers doesn't naturally work with pm2.  I don't know why, but something about the way it works totally doesn't work.

**Comment by edwardsmarkf** [comment]
this worked for me:

 /usr/local/bin/pm2      start  /path/to/feathersServer   -- --port 8005  ;


Thank you,

Mark Edwards
