### ISSUE TITLE
Comment:Step-Basic-About-Hooks-2

### ISSUE THREAD

**Issue by Piliponful** [feathersjs/feathers-docs#766]
Comment:Step-Basic-About-Hooks-2
The title is "All about hooks" and it's not even first page on hooks. So I start adding them in my test app. It obviously throw error because I didn't add feathers-hooks. So your question was "Is anything wrong, unclear, missing?". And I say yes, this is what was definitely unclear to me.

**Comment by eddyystop** [comment]
Chapters:
- Hooks middleware
- All about hooks
- Hooks, part 1
- Hooks, part 2
- Writing your own hooks
- Testing hooks


"All about hooks", just like the previous page "Hooks Middleware", talks about the design of hooks and how hooks at different levels interact. 

The code snippets it shows, such as
```javascript
app.hooks({
  before: {
    create: hook30a
  },
  after: {
    create: hook39a
  },
});
```
are included to relate the diagrams to code fragments. They are not working code because of all the undefined variables.

Once this design has been explained, the following pages go into considerable detail on the coding of provided and custom hooks. You would have avoided your issue if you had continued reading.


Please feel free to reopen this issue.
